### ISSUE TITLE
Give a choice of which specific hash algos to use?

### ISSUE THREAD

**Issue by neuro18** [gurnec/HashCheck#2]
Hi,

Is it possible to remove (or disable by default) CRC-32 and MD4 from the app? These hash functions are obviously obsolete nowadays. Also, do you have plans to add SHA-512 support? And possibly let a user to choose which specific hash functions to use by default (through additional options)?

Thanks!

**Comment by RomelSan** [comment]
I agree, add an option to select specific hash algos to use.

**Comment by LtPinback** [comment]
I agree on giving the user the option to choose which hash functions to calculate but disagree on removing any from the app. CRC-32 is enough for data integrity checks where safety is not an issue.

**Comment by gurnec** [comment]
SHA-512 has been added, and MD4 removed. CRC-32 is still present (and I agree, it's still useful for data integrity, just not for security-related purposes).

All credit for these improvements (and many others) goes to @modelrockettier, thanks!

A new installer will be uploaded with these updates in a week or two.

I agree a choice of which hash algorithms to use would be nice; I'll keep this open until this has been implemented.

**Comment by gurnec** [comment]
FYI the latest binary version of HashCheck with SHA-512 support is [available for download here](https://github.com/gurnec/HashCheck/releases).
