### ISSUE TITLE
Add sha256 and sha512 file types to "Save as" dialog

### ISSUE THREAD

**Issue by XP1** [gurnec/HashCheck#26]
**Add sha256 and sha512 file types to "Save as" dialog**

Under "Right click > Create Checksum File... > Save as type:", there should be sha256 and sha512 file types.

![hashcheck - save as file type](https://cloud.githubusercontent.com/assets/776585/24265545/4d021f6e-0fda-11e7-8c50-0eb53c77d678.png)

**Comment by rddim** [comment]
You can try the 2.4.1.58-alpha from https://ci.appveyor.com/project/gurnec/hashcheck/build/2.4.1.58-alpha/artifacts

**Comment by XP1** [comment]
@rddim, thanks.
