### ISSUE TITLE
SHA-3 support

### ISSUE THREAD

**Issue by fda77** [gurnec/HashCheck#3]
Thanks for you work gurnec! Can you add sha-512 too?

**Comment by y888** [comment]
Can you add sha3 = =

**Comment by gurnec** [comment]
SHA-512 support has been added.

All credit for this improvement (and many others) goes to @modelrockettier, thanks!

A new installer will be uploaded with SHA-512 in a week or two.

I agree SHA3 support would be nice; I'll keep this open until this has been implemented.

**Comment by gurnec** [comment]
FYI the latest binary version of HashCheck with SHA-512 support is [available for download here](https://github.com/gurnec/HashCheck/releases).
