### ISSUE TITLE
Windows upgrade breaks HashCheck

### ISSUE THREAD

**Issue by patrickli** [gurnec/HashCheck#38]
I upgrade my windows 10 to 1709 recently and HashCheck stopped working.

A brief check reveals that windows upgrade process has deleted `Windows\(System32|SysWOW64)\ShellExt` folders which contains `HashCheck.dll`.

Installing `HashCheck.dll` into `Program Files` and `Program Files (x86)` folders should fix this issue.

**Comment by scara** [comment]
Hi @patrickli,
this is a duplicated of #15: please, read this comment too, there: https://github.com/gurnec/HashCheck/issues/15#issuecomment-336613105.

HTH,
Matteo

**Comment by patrickli** [comment]
Sure.

**Comment by ZPNRG** [comment]
Yes, every Windows 10 major update breaks HashCheck v2.4.0 and you have to reinstall it. It is easy and fast to reinstall, but would be nice to see this fixed.
