### ISSUE TITLE
Windows Libraries Folder Focus

### ISSUE THREAD

**Issue by TeslaMagic** [gurnec/HashCheck#4]
This isn't a real "issue" with HashCheck but a request for a suggestion or workaround.

Is there a trick to force Windows Explorer to focus on Library folders when creating a checksum file?
If you highlight files within any Libraries folder/directory, then right click and select "Create Checksum File....", when the Save As dialog appears, the focus is not on the current folder.

The "Save As" focuses correctly when used on folders/directories outside of Libraries.

Any suggestion would be appreciated.

**Comment by gurnec** [comment]
I suspect this is an OS bug, but I'm not sure. I can't reproduce it on Windows 10 - when I select "Create Checksum File..." on a file inside a library (after enabling libraries in Explorer, their display is disabled by default in Windows 10), the correct library folder is highlighted on the left and the destination folder also matches up correctly.

Unless perhaps I'm misunderstanding what you're describing?

**Comment by TeslaMagic** [comment]
Thank you for the information gurnec. I have been using third party file managers instead of Windows Explorer and they all work fine. I have also disabled Windows Libraries and everything works fine as well.

You can probably delete this "issue" since it is an operating system problem. Simplest solution is to disable the libraries function.
