### ISSUE TITLE
Sort table by headers

### ISSUE THREAD

**Issue by gingerbeardman** [gurnec/HashCheck#49]
It would be great if we could sort table by headers, so I can easily see all MISMATCH lines.

Alternatively, a way to filter table would be good to hide everything other than a chosen status.

Currently, headers are clickable but no sort or filtering happens.

**Comment by R-Adrian** [comment]
sorting by clicking on headers works for me... but you have to wait for the check to finish so that the list is not modified anymore.

if you click on headers while it's still checking files, then yes, it won't sort the list because it's still building it.

**Comment by gingerbeardman** [comment]
Ah,  thanks for that!
