### ISSUE TITLE
An obvious newbs question: How to install and run HashCheck?

### ISSUE THREAD

**Issue by Stumpjumper64** [gurnec/HashCheck#5]
I've downloaded and un-zipped the files. But after perusing the files at the level of their names and file types it's not clear whether an executable installation file exists nor can I find notes on where to store the files/directories and run the tool. Can someone help, please?

Apologies for this low level request for assistance in advance.

**Comment by chappjc** [comment]
I think you're looking for the Release where there is an installer.
https://github.com/gurnec/HashCheck/releases

**Comment by ryanneve** [comment]
Thanks for the answer. I am curious as to the original question. I've got VS 2015 installed, but mostly use it with microcontrollers. Would love to be able to build and install windows programs from source. I tried building this, but just got a .dll. There must be a procedure for building an installer.

**Comment by chappjc** [comment]
@ryanneve Oh, now I see.  You need to compile HashCheck.nsi to build the setup exe.  Just install the [Nullsoft Installer](http://nsis.sourceforge.net/Download) and you will have a context menu item called "Compile NSIS Script" for the .nsi file in Windows Explorer.

**Comment by gurnec** [comment]
Thanks for your help, @chappjc!
