### ISSUE TITLE
Clipboard compare

### ISSUE THREAD

**Issue by loquiter** [gurnec/HashCheck#59]
Since many websites merely show the file hash on the download web page, rather than have a downloadable file that HashCheck can use, it would be tremendously helpful to automatically compare file hashes against a value pulled from the Windows clipboard.

**Comment by LanceUMatthews** [comment]
If there's no hash file to verify against, then you must be interacting with HashCheck via the `Checksums` tab of a file/directory `Properties` dialog.  In that case, pasting text (i.e. a hash) into the `Find` field at the bottom will highlight it, if found, in the text area above.

**Comment by loquiter** [comment]
I guess they must not have matched somewhere off to the right out of the window when I tried it.  I thought that "Find" must've been for something else X-D
