### ISSUE TITLE
[Request] sha2 File Association

### ISSUE THREAD

**Issue by ghost** [gurnec/HashCheck#63]
is there any way to add file association for sha2 files?

**Comment by R-Adrian** [comment]
1) regedit.exe
2) go to `[HKEY_CLASSES_ROOT\.sha256]`
3) export the entire key
4) open the exported file in notepad
5) (in notepad) find&replace all ".sha256" with ".sha2"
6) save the modified file
7) double-click on the modified .REG file to import back in registry

**Comment by ghost** [comment]
Thank you very much.

**Comment by garoto** [comment]
Alternatively, a one-liner from a `cmd` prompt:

```
C:\>reg add "HKEY_CLASSES_ROOT\.sha2" /ve /d "HashCheck" && reg add "HKEY_CLASSES_ROOT\.sha2" /v "PerceivedType" /d "text" && reg add "HKEY_CLASSES_ROOT\.sha2\PersistentHandler" /ve /d "{5e941d80-bf96-11cd-b579-08002b30bfeb}"
```
