### ISSUE TITLE
how to track and look at the HashCheck in the proecesses from the task managaer 

### ISSUE THREAD

**Issue by DEVUVO** [gurnec/HashCheck#82]
Hello , how to track and look at the HashCheck in the proecesses from the task managaer  , cant find any process for it ?

**Comment by LanceUMatthews** [comment]
HashCheck is a Windows/File Explorer extension, so look for `explorer.exe`.

**Comment by DEVUVO** [comment]
awesome , i see it now , thank you for quick response you are awesome.
