### ISSUE TITLE
SHA-2 is missing?

### ISSUE THREAD

**Issue by err0rsys** [gurnec/HashCheck#90]
Hi,
I don't see an option to calculate SHA-2. This is a very popular way to calculate a hash from a file.
Has it been removed?

**Comment by NintendoManiac64** [comment]
~~I don't believe it was ever present and development on HashCheck Shell Extension went straight from the SHA1 family of checksums (primarily SHA256 and SHA512) to the SHA3 family of checksums, skipping over the SHA2 family of checksums altogether.~~

**EDIT:** I am wrong; see the following comment.

**Comment by crzsotona** [comment]
SHA-1 digest is 160 bits only, SHA-256 and SHA-512 is standard naming for SHA-2, so the whole discussion is pointless.
Source:
https://en.wikipedia.org/wiki/SHA-1
https://en.wikipedia.org/wiki/SHA-2

**Comment by err0rsys** [comment]
> SHA-1 digest is 160 bits only, SHA-256 and SHA-512 is standard naming for SHA-2, so the whole discussion is pointless. Source: https://en.wikipedia.org/wiki/SHA-1 https://en.wikipedia.org/wiki/SHA-2

You're right. When someone gives SHA-2 for comparison, it's probably SHA-256 by default.
